### ISSUE TITLE
Import Issue for markllm.evaluation.tools

### ISSUE THREAD

**Issue by hwq0726** [THU-BPM/MarkLLM#25]
Hi,

I encountered a `ModuleNotFoundError` when attempting to import from the `markllm.evaluation.tools` module. Below is the snippet of code I used:
`from markllm.evaluation.tools.text_editor import TruncatePromptTextEditor, WordDeletion`
The error message received was:
`ModuleNotFoundError: No module named 'markllm.evaluation.tools'`

Upon checking the directory structure, it appears that the `tools` folder is missing under the `evaluation` directory.

Could you please look into this? I appreciate your efforts on this project and look forward to a resolution. Thank you!

**Comment by panly2003** [comment]
Thank you for your feedback. I suggest checking if you've accidentally deleted the tools folder from your local copy of the project.

Please verify your local MarkLLM/evaluation/ directory to ensure the tools folder is present. If it's missing, you may need to restore it from the GitHub repository.

**Comment by hwq0726** [comment]
I used pip to install the package and I'm pretty sure I didn't delete anything.
Also, I check the download files here [https://pypi.org/project/markllm/#files](url), the tools fold is missing.

**Comment by panly2003** [comment]
Thank you for bringing this to our attention. We apologize for the oversight in our pip packaging process, where we inadvertently omitted the tools/ folder. We've rectified this issue by repackaging and uploading a new version. Please try running pip install again to get the updated package.

Additionally, we highly recommend using git clone to access the repository instead of pip. This method provides more flexibility in adjusting configurations and ensures you have access to the most up-to-date version of the toolkit. 😊

**Comment by hwq0726** [comment]
Many thanks!
