### ISSUE TITLE
pip package out of sync with main

### ISSUE THREAD

**Issue by fabriceyhc** [THU-BPM/MarkLLM#37]
I could just use a local clone, but using the pip package for all the watermark techniques would be nicer. 

For example, SynthID doesn't work in the pip package. 

Missing from `markllm/watermark/auto_watermark.py`:

```
    'SynthID': 'markllm.watermark.synthid.SynthID'
```

**Comment by panly2003** [comment]
Thank you very much for your reminder! The pip package is indeed currently out of sync with the GitHub repository. Since using a git clone allows for more flexible configuration modifications, we recommend that users consider this option. We sincerely appreciate your understanding and will make an effort to update the pip package as soon as we can.
