### ISSUE TITLE
EXP-Gumbel

### ISSUE THREAD

**Issue by redwyd** [THU-BPM/MarkLLM#38]
Could you tell me which algorithm in the original paper EXP-Gumbel implements and why the F1 value of detection is only 0.66?

**Comment by panly2003** [comment]
Thank you for your question! As mentioned in the README, EXP-Gumbel is an equivalent implementation of EXP that utilizes Gumbel max sampling. The temperature parameter is used to adjust the watermark strength; a higher temperature results in a stronger watermark.

Regarding the F1 value of 0.66, this may be due to the previous default configuration setting the temperature to 0.2. We have since updated it to 0.7. Thank you for bringing this to our attention!

**Comment by redwyd** [comment]
I tried changing the temperature from 0.2 to 0.7, but the F1 value didn’t seem to change.

**Comment by panly2003** [comment]
Have you evaluated the algorithm using the test_detection_pipeline in test/test_pipeline.py? If you did, it seems you might have left the WordDeletion in the text editor list. While this was included to test the algorithm's robustness, it should be removed when evaluating performance under normal conditions (no attack scenario). Also, please ensure you've set reverse=True in DynamicThresholdSuccessRateCalculator, since for EXPGumbel, a lower p-value indicates stronger watermark presence. I've tested EXPGumbel's performance and achieved an F1 score of 0.99 using the code below.
![image](https://github.com/user-attachments/assets/bfbebc16-4e76-4713-ad59-67943bc877bf)

**Comment by redwyd** [comment]
OK! I got it! I forgot to set reverse=True, Thanks!
