### ISSUE TITLE
Naming for the EXP algorithm

### ISSUE THREAD

**Issue by lilakk** [THU-BPM/MarkLLM#7]
Hi all,

Thanks for the valuable work! I have a quick question about the naming of the EXP algorithm. Authors of the "Robust Distortion-free Watermarks for Language Models" paper refer to their variant based on the Aaronson watermark as "EXP" in their work, while MarkLLM seem to refer to the original Aaronson watermark by "EXP". So just to confirm, the "EXP" in MarkLLM is different from the "EXP" in the distortion-free paper, right?

**Comment by panly2003** [comment]
Thank you for your question regarding the naming conventions for the EXP algorithm. 

The EXP algorithm in MarkLLM refers to the original Aaronson algorithm, as it uses the exp-minimum sampling method. However, in the MarkLLM project, we have also implemented the variant based on exp-minimum sampling proposed in the "Robust Distortion-free Watermarks for Language Models" paper. Since this variant introduces the concept of edit distance on top of the original Aaronson algorithm, we refer to it as EXP-Edit to distinguish it from the original EXP algorithm.

Always happy to help. 😊

**Comment by lilakk** [comment]
Ah yes I understand the main algorithm they're promoting is called EXP-Edit, but in their paper they also have a method called EXP, which is a variant of the Aaronson watermark. I just wanted to check if your EXP is the original Aaronson watermark, sorry for the confusion and thanks for answering my question!
